issuu_viewer.settings:
  type: config_object
  label: 'Issuu viewer settings'
  mapping:
    issuu_viewer_default_background:
      type: string
      label: 'The default background color for Issuu viewer'
    issuu_viewer_default_height:
      type: integer
      label: 'The default height size for Issuu viewer'
